### ISSUE TITLE
Error with Bootstrap nav-toggler button in mobile screen (Dimension: Pixel 3)

### ISSUE THREAD

**Issue by Msadeq12** [Msadeq12/ClassRoom#1]
The button does not show the links to the Login page or the Sign up page. 

<img width="330" alt="Screen Shot 2022-02-15 at 9 49 43 PM" src="https://user-images.githubusercontent.com/54909392/154187040-f169ab0b-8078-4715-9e3f-4b8a34b561c7.png">

**Comment by zuhaiir** [comment]
![image](https://user-images.githubusercontent.com/20420568/155412452-dd238fae-bee8-4723-953c-38153d43b52f.png)
The javascript library part of bootstrap was not included. That was why the nav wasn't working. I am confused as to why we are using bootstrap 4.5 though.
